title: maibennett
description: Repository of presentations
url: "https://www.magdalenabennett.com"
twitter_username: maibennett
github_username: maibennett

show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
