title = "maibennett"
baseURL = "https://www.magdalenabennett.com"
languageCode = "en-us"

logo = "/images/ggplot2_masterpiece.png"

theme = "minima"

[params]
  favicon = "favicon.ico"
  site_logo = ""
  description = "Presentation repository"
