title = "maibennett"
baseURL = "https://www.magdalenabennett.com"
languageCode = "en-us"

logo= "/images/ggplot2_masterpiece.png"

theme = "ananke"

[params]
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = "Presentation repository"
  facebook = ""
  twitter = "https://twitter.com/maibennett"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/ggplot2_masterpiece.png"
