---
title: "How far is too far? <br/>Estimation of an interval for generalization of a regression discontinuity design away from the cutoff"
subtitle: "Magdalena Bennett"
author: "International Methods Colloquium<br/>Mar 12, 2021"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
    includes:
      in_header: header.html
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.showtext = TRUE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)

theme_xaringan(
  text_color = "#333f48",
  background_color = "#FFFFFF",
  accent_color = "#900DA4",
  text_font = "Fira Mono",
  text_font_use_google = TRUE,
  title_font = "Fira Sans Condensed",
  title_font_use_google = TRUE
)

style_mono_accent(
  #base_color = "#bf5700",
  extra_fonts = list(google_font("Fira Sans","200","300","400","500","600"),
                     google_font("Fira Sans Condensed")),
  base_color = "#333f48",
  header_font_google = google_font("Yanone Kaffeesatz","200","300","400","500","600","700"),
  text_font_google   = google_font("Jost", "300", "300i","400","500"),
  code_font_google   = google_font("Fira Mono"),
  text_bold_color = "#333f48",
  text_font_size = "110%",
  colors = c(
    red = "#f34213",
    purple = "#900DA4",
    orange = "#ff8811",
    green = "#136f63",
    white = "#FFFFFF"),
  extra_css = list(
    ".remark-slide table" = list("display" = "table",
                   "width" = "80%",
                   "text-align" = "left"),
    ".remark-slide-number" = list("display" = "none"),
    ".strong" = list("font-weight" = "400"),
    ".big" = list("font-size" = "350%",
                     "font-family" = "Yanone Kaffeesatz",
                     "font-weight"="400"),
    ".small" = list("font-size" = "80%"),
    ".source" = list("color" = "#8c8c8c",
                     "font-size" = "80%"),
    ".remark-slide table td#highlight" = list("background-color" = "#eee1f0",
                                  "color" = "#900DA4",
                                  "font-weight" = "500"),
   # ".remark-slide table thead th" = list(),
    ".title-slide h1" = list("font-weight" = "500"),
    ".title-slide h2" = list("font-weight" = "400",
                             "font-size" =  "170%"),
    ".title-slide h3" = list("font-family" = "Jost",
                             "font-size" = "100%",
                             "font-weight" = "200"),
    ".center2" = list("margin" = "0",
                      "position" = "absolute",
                      "top" = "50%",
                      "left" = "50%",
                      "-ms-transform" = "translate(-50%, -50%)",
                      "transform" = "translate(-50%, -50%)"),
    ".section-title h1" = list("color" = "#FFFFFF",
                               "font-size" = "2.3em",
                               "line-height" = "1.3"),
    ".medium" = list("font-size" = "1.4em"),
    ".sp-after-half" = list("margin-bottom" = "0.7em !important"),
    ".box-1,.box-1a,.box-1b,.section-title-1" = list("background-color" = "#0D0887"),
    ".box-2,.box-2a,.box-2b,.section-title-2" = list("background-color" = "#5601A4"),
    ".box-3,.box-3a,.box-3b,.section-title-3" = list("background-color" = "#900DA4"),
    ".box-4,.box-4a,.box-4b,.section-title-4" = list("background-color" = "#BF3984"),
    ".box-5,.box-5a,.box-5b,.section-title-5" = list("background-color" = "#E16462"),
    ".box-6,.box-6a,.box-6b,.section-title-6" = list("background-color" = "#F89441"),
    ".box-7,.box-7a,.box-7b,.section-title-7" = list("background-color" = "#FCCE25"),
    ".box-7, .box-6, .box-5, .box-4, .box-3, .box-2, .box-1" = list("color" = "#FFFFFF",
                                                                    "margin" = "0em auto",
                                                                    "overflow" = "hidden",
                                                                    "padding" = "0.4em 0.4em",
                                                                    "font-weight" = "600",
                                                                    "font-size" = "31px",
                                                                    "display" = "table",
                                                                    "text-align" = "center",
                                                                    "font-family" = "Fira Sans"),
    ".box-7a, .box-6a, .box-5a, .box-4a, .box-3a, .box-2a, .box-1a" = list("color" = "#FFFFFF",
                                                                          "left" = "0px",
                                                                          "overflow" = "hidden",
                                                                      "padding" = "0.4em 0.4em",
                                                                      "font-weight" = "600",
                                                                      "font-size" = "25px",
                                                                      "display" = "table",
                                                                      "text-align" = "center",
                                                                      "font-family" = "Fira Sans"),
       ".box-7b, .box-6b, .box-5b, .box-4b, .box-3b, .box-2b, .box-1b" = list("color" = "#FFFFFF",
                                                                          "left" = "0px",
                                                                          "overflow" = "hidden",
                                                                      "padding" = "0.4em 0.4em",
                                                                      "font-weight" = "600",
                                                                      "font-size" = "25px",
                                                                      "display" = "table",
                                                                      "text-align" = "left",
                                                                      "font-family" = "Fira Sans")
  )
)

#,"li" = list("font-size" = "150%")
#    "li" = list("font-size" = "110%"),
#    "ul" = list("font-size" = "110%"),
#color palette
#5601A4
#900DA4
#F89441
#FCCE25
```

```{r setup2, echo=FALSE, message=FALSE, warning = FALSE}
library(knitr)
library(showtext)
library(xaringanExtra)

xaringanExtra::use_scribble()

```

```{r fonts, message=FALSE, echo=FALSE, warning = FALSE}
font_add_google("Fira Sans Condensed", "Fira Sans Condensed")
font_add_google("Fira Sans", "Fira Sans")
font_add_google("Jost", "Jost")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gganimate)
library(ggthemes)
library(gifski)
library(plotly)
library(leaflet)
library(ggplot2)
library(firasans)
library(hrbrthemes)
library(extrafont)
library("RColorBrewer")
library(viridis)
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("firasans")
library(hrbrthemes)
library(extrafont)

options(scipen = 0)
```

# Regression discontinuity design

```{r rd_intro1, fig.height=5.25, fig.width=12, fig.align='center', dev='svg', echo = FALSE, warning = FALSE, message = FALSE}

set.seed(100)

n = 500

r = rnorm(n, 10,7)

treat = as.numeric(r>=10)

y = 2 - 1.5*(10-r) + 18*treat + 0.5*treat*(10-r) -  0.05*treat*(10-r)^2 + rnorm(n,0,7)

d = data.frame("r" = r,
               "treat" = treat,
               "y" = y)

ggplot(data = d, aes(x=r, y=y)) +
  geom_point(size = 3, pch = 21, color = "dark grey", fill="white") +
  geom_vline(aes(xintercept=10), lty = 2, color = "#333f48", lwd = 1.5) +
  ggplot2::annotate("rect", color="white", fill="white", xmin = 7, xmax = 13, ymin=38, ymax = 48) +
  ggplot2::annotate("text", label = "Cutoff", size = 10, hjust = 0.5, x = 10, y = 43, color = "#333f48",
                    family = "Fira Sans Condensed")+
  theme_bw() +
  theme_ipsum_fsc()+
  xlab("Running variable") + ylab("Outcome") + 
  theme(plot.margin=unit(c(1,1,1.5,1.2),"cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "light grey"),
        panel.grid.minor.y = element_blank(),
        axis.line = element_blank())+
  theme(axis.title.x = element_text(size = 24, color = "#333f48"),#margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_blank(),
        axis.title.y = element_text(size = 24, color = "#333f48"),#margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.text.y = element_blank(),legend.position="none",
        legend.title = element_text(size=12),
        legend.text = element_text(size=10),
        legend.background = element_rect(fill="white",colour ="white"),
        title = element_text(size=12))


```

---
# Increasingly popular method


```{r rd_publications, fig.height=5.25, fig.width=12, fig.align='center', dev='svg', echo = FALSE, warning = FALSE, message = FALSE}
d <- read.csv("https://raw.githubusercontent.com/maibennett/presentations/main/content/presentations/RD/IC_20210312/data/regression_discontinuity.csv")
```